english_to_arabic = {
    'Al': 'ال',
    'Alef': 'ا',
    'Alef': 'أ',
    'Beh': 'ب',
    'Teh': 'ت',
    'Theh': 'ث',
    'Jeem': 'ج',
    'Hah': 'ح',
    'Khah': 'خ',
    'Dal': 'د',
    'Thal': 'ذ',
    'Reh': 'ر',
    'Zain': 'ز',
    'Seen': 'س',
    'Sheen': 'ش',
    'Sad': 'ص',
    'Dad': 'ض',
    'Tah': 'ط',
    'Zah': 'ظ',
    'Ain': 'ع',
    'Ghain': 'غ',
    'Feh': 'ف',
    'Qaf': 'ق',
    'Kaf': 'ك',
    'Lam': 'ل',
    'Meem': 'م',
    'Noon': 'ن',
    'Heh': 'هـ',
    'Waw': 'و',
    'Yeh': 'ي',
    'Teh_Marbuta': 'ة',
    'Laa': 'لا'
}

